name: utils build
on:
  workflow_call:    

jobs:
  build-utils:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/prb17/ubuntu-dev:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout my code
      uses: actions/checkout@v3
      with: 
        submodules: 'true'
    
    - name: build utils
      run: |
        mkdir build
        cd build
        cmake -DBUILD_UTILS_TESTS=ON --log-level debug ..
        make -j4 install

    - name: Upload utils install
      uses: actions/upload-artifact@v3
      with:
        name: utils_install
        path: ./install
