name: utils build

on: push
  # push:
  #   tags:
  #     - '*'
  #   branches:
  #     - 'main'

jobs:
  build-utils:
    uses: ./.github/workflows/utils-build.yml
  test-utils:
    runs-on: ubuntu-latest
    needs: [build-utils]
    container:
      image: ghcr.io/prb17/ubuntu-dev:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Download utils installed binaries
      uses: actions/download-artifact@v3
      with:
        name: utils_install

    - name: Container Tests
      run: |
        export LD_LIBRARY_PATH=`pwd`/parsers/lib:`pwd`/third_party/jsoncpp/lib
        cd structures/bin
        chmod +x container_test
        valgrind --leak-check=full --error-exitcode=1 ./container_test ../config/arrays/container_test_*.json
        chmod -x container_test
        cd -

    - name: Array Tests
      run: |
        export LD_LIBRARY_PATH=`pwd`/parsers/lib:`pwd`/third_party/jsoncpp/lib
        cd structures/bin
        chmod +x arrays_test
        valgrind --leak-check=full --error-exitcode=1 ./arrays_test ../config/arrays/array_test_*.json
        chmod -x arrays_test
        cd -
        
    - name: Stack Tests
      run: |
        export LD_LIBRARY_PATH=`pwd`/parsers/lib:`pwd`/third_party/jsoncpp/lib
        cd structures/bin
        chmod +x stacks_test      
        valgrind --leak-check=full --error-exitcode=1 ./stacks_test ../config/stacks/stack_test_*.json
        chmod -x stacks_test
        cd -

    - name: Queue Tests
      run: |
        export LD_LIBRARY_PATH=`pwd`/parsers/lib:`pwd`/third_party/jsoncpp/lib
        cd structures/bin
        chmod +x queues_test      
        valgrind --leak-check=full --error-exitcode=1 ./queues_test ../config/queues/queue_test_*.json
        chmod -x queues_test
        cd -

    - name: Graph Tests
      run: |
        export LD_LIBRARY_PATH=`pwd`/parsers/lib:`pwd`/third_party/jsoncpp/lib
        cd structures/bin
        chmod +x graphs_test      
        valgrind --leak-check=full --error-exitcode=1 ./graphs_test ../config/graphs/graph_test_*.json
        chmod -x graphs_test
        cd -

    - name: Lists Tests
      run: |
        export LD_LIBRARY_PATH=`pwd`/parsers/lib:`pwd`/third_party/jsoncpp/lib
        cd structures/bin
        chmod +x linked_list_test      
        valgrind --leak-check=full --error-exitcode=1 ./linked_list_test ../config/graphs/linked_lists/linked_lists_test_*.json
        chmod -x linked_list_test
        cd -
